Models/ViewModels/ArchivoViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Login_MVC.Models.ViewModels
{
    public class ArchivoViewModels
    {
        [Required]
        [DisplayName("Mi Archivo")]
        public HttpPostedFileBase Archivo1 { get; set; }

        [Required]
        [DisplayName("Mi Archivo 2")]
        public HttpPostedFileBase Archivo2 { get; set; }
        [Required]
        [DisplayName("Mi Cadena")]
        public string Cadena { get; set; }
    }
}

Controllers/ArchivoController.cs
using Login_MVC.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Login_MVC.Controllers
{
    public class ArchivoController : Controller
    {
        // GET: Archivo
        public ActionResult Index()
        {
            if (TempData["Message"] != null)
                ViewBag.Message = TempData["Message"].ToString();
            return View();
        }

        [HttpPost]
        public ActionResult Save(ArchivoViewModels model)
        {
            try
            {
                string RutaSitio = Server.MapPath("~/");
                string PathArchivo1 = Path.Combine(RutaSitio + "/Files/archivo1.jpg");
                string PathArchivo2 = Path.Combine(RutaSitio + "/Files/archivo2.jpg");

                if (!ModelState.IsValid){

                    return View("Index",model);
                }
                model.Archivo1.SaveAs(PathArchivo1);
                model.Archivo2.SaveAs(PathArchivo2);

                @TempData["Message"] = "Se cargaron los archivos";

                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return Redirect(ex.Message);
            }
        }
    }
}

Views/Archivo/Index.cshtml
@model Login_MVC.Models.ViewModels.ArchivoViewModels
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if (ViewBag.Mesage != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}


@using (Html.BeginForm("Save","Archivo",FormMethod.Post, new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken();
    <div class="row">
        <div class="col-md-6 col-lg-offset-6">
            <div class="form-group">
                @Html.LabelFor(d => d.Archivo1)
                @Html.TextBoxFor(d => d.Archivo1, new { @class = "form-control", type = "file", accept = ".jpg" })
                @Html.ValidationMessageFor(d => d.Archivo1, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(d => d.Archivo2)
                @Html.TextBoxFor(d => d.Archivo2, new { @class = "form-control", type = "file", accept = ".jpg" })
                @Html.ValidationMessageFor(d => d.Archivo2, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(d => d.Cadena)
                @Html.TextBoxFor(d => d.Cadena, new {@class="form-control"})
                @Html.ValidationMessageFor(d => d.Cadena, "", new { @class = "text-danger" })
            </div>

            <div class="form-group" style="text-align:right;">
                <input type="submit" class="btn btn-success" value="Guardar"/>
            </div>
        </div>
    </div>
}